services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: golfclub
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - golfclub_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p=password"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: golfclub_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/golfclub
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - golfclub_net

volumes:
  mysql-data:

networks:
  golfclub_net:
